(defun c:M-set ( / )
(SETQ OBJ (car (entsel)))
(dumpallproperties OBJ 1)
(PRINT (getpropertyvalue OBJ "Model Role"))
(PRINT (ispropertyreadonly OBJ "Model Role"))
(PRINT (getpropertyvalue OBJ "Pre defined remark"))
(PRINT (ispropertyreadonly OBJ "Pre defined remark"))
(PRINT (getpropertyvalue OBJ "User Attribute 03"))
(PRINT (ispropertyreadonly OBJ "User Attribute 03"))
)

(defun c:M-set ( / )
(SETQ OBJ (VLAX-ENAME->VLA-OBJECT(car (entsel))))
		(print (vlax-dump-object OBJ T))

(DEFUN C:INFO ( / OBJ )
	(SETQ OBJ (car (entsel)))
	(PRINT "dxf OUTPUT")
	(foreach  p (ENTGET OBJ)
		(PRINT p)
	)
	(PRINT "Properties Dunp")
	(dumpallproperties OBJ 1)
	(PRINT "VLX Dump")
	(print (vlax-dump-object (VLAX-ENAME->VLA-OBJECT OBJ) T))
)

(DEFUN C:TEST ( / OBJ )
	(SETQ OBJ (car (entsel)))
	(setpropertyvalue OBJ "AcDbDynBlockPropertyPanel Length" 240)
	(setpropertyvalue OBJ "COLOR" "QC8262 Black")
	)


;;toggles a specified layer on and off layer defind by "0" 	
(defun c:layertest (/ linfo )
	(if (setq linfo (tblsearch "layer" "0"))
		(progn
			(if (= (cdr (assoc '70 linfo)) 1)
				(command "-layer" "t" (cdr (assoc '2 linfo)) "")
				(command "-layer" "f" (cdr (assoc '2 linfo)) "")				
			)
			(if (minusp (cdr (assoc '62 linfo)))
				(command "-layer" "on" (cdr (assoc '2 linfo)) "")
			)
		)
		(print "dose not exist")
	)
	(print linfo)
)
